import { error, info } from "console";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        none: "0",
        nano: "4px",
        quack: "6px",
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        pill: "500px",
        circular: "50%",
      },
      borderWidth: {
        none: "0",
        hairline: "1px",
        thin: "2px",
        thick: "4px",
        heavy: "8px",
        black: "16px",
      },
      boxShadow: {
        "level-1": "0px 4px 8px rgba(0, 0, 0, 0.5)",
        "level-2": "0px 8px 24px rgba(0, 0, 0, 0.5)",
        "level-3": "0px 16px 32px rgba(0, 0, 0, 0.5)",
        "level-4": "0px 16px 48px rgba(0, 0, 0, 0.5)",
      },
      colors: {
        brand: {
          100: "#D9EFFF",
          600: "#1C7EF4",
          700: "#1567E2",
          800: "#1853B5",
        },
        neutral: {
          0: "#FFFFFF",
          50: "#fafafa",
          100: "#F5F5F5",
          200: "#E5E5E5",
          300: "#D4D4D8",
          400: "#A3A3A3",
          500: "#71717A",
          600: "#525252",
          700: "#525252",
          800: "#262626",
          900: "#18181b",
          950: "#0A0A0A",
        },
        error: {
          100: "#FEE2E2",
          600: "#DC2626",
          900: "#7F1D1D",
          950: "#450A0A",
        },
        success: {
          100: "#DCFCE7",
          600: "#16A34A",
          900: "#14532D",
          950: "#052E16",
        },
        warning: {
          100: "#FEF3C7",
          600: "#D97706",
          900: "#78350F",
          950: "#451a03",
        },
        info: {
          100: "#E0F2FE",
          600: "#0284C7",
          900: "#0C4A6E",
          950: "#082F49",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        sans: ["Poppins", "sans-serif"],
      },
      letterSpacing: {
        large: "-2%",
        medium: "-1%",
        default: "0",
      },
      lineHeight: {
        default: "100%",
        xs: "115%",
        sm: "120%",
        lg: "140%",
      },
      opacity: {
        solid: "1",
        "semi-opaque": "0.72",
        intense: "0.56",
        medium: "0.4",
        light: "0.16",
        "semi-transparent": "0.04",
      },
      padding: {
        quarck: "4px",
        nano: "8px",
        xs: "12px",
        xxs: "16px",
        sm: "24px",
        md: "32px",
      },
      screens: {
        "3xl": "2000px",
      },
      spacing: {
        quarck: "4px",
        nano: "8px",
        xxxs: "16px",
        xxs: "24px",
        xs: "32px",
        sm: "40px",
        md: "48px",
        lg: "56px",
        xl: "64px",
        xxl: "80px",
        xxxl: "120px",
        huge: "160px",
        giant: "200px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
